name: apps-stack

include:
  - ./compose.open-webui.yaml
  - ./compose.homepage.yaml
  - ./compose.it-tools.yaml
  - ./compose.upsnap.yaml
  - ./compose.freshrss.yaml
  - ./compose.full-text-rss.yaml
