services:

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    restart: always
    privileged: true
    env_file:
      - ./provision/esphome.env
      - path: ./provision/esphome.prod.env
        required: false
    volumes:
      - ./volumes/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "6052:6052"
